export const ActionType = {
    UPDATE_CLIENT_LIST: "UPDATE_CLIENT_LIST",
    UPDATE_CURRENT_SHIRT: "UPDATE_CURRENT_SHIRT",
    UPDATE_CART_LIST: "UPDATE_CART_LIST",
    DELETE_CURRENT_SHIRT: "DELETE_CURRENT_SHIRT",
  };